
spring:
#  配置数据库
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 12345678
     url: jdbc:mysql://localhost:3306/cat_hospital_up
    #配置数据库连接池
     type: com.alibaba.druid.pool.DruidDataSource
   redis:
     #url: redis://user:password@127.0.0.1:6379 #该地址配置以后会重置host,port,password的规则。
     host: 127.0.0.1
     port: 6379
     #密码默认为空
     #password: 123456
     database: 0 #指定数据库，默认为0
     timeout: 300 #连接超时时间，单位毫秒，默认为0
     ssl: false # 是否启用SSL连接，默认false
     jedis:
       pool: #连接池配置
         max-active: 8 #最大活跃连接数，默认8个。
         max-idle: 8 #最大空闲连接数，默认8个。
         max-wait: -1 #获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况。
         min-idle: 0 #最小空闲连接数，默认0。
     #sentinel:
     #    master: mymaster #哨兵mastser
     #    nodes: host1:port,host2:port #哨兵节点
     #cluster:
     #    max-redirects: # 集群模式下，集群最大转发的数量
     #    nodes: host1:port,host2:port # 集群节点



#配置mapperXml的路径
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
#配置后端端口
server:
  port: 7899


